name: WordPress Coding Standards
on: [push]
jobs:
  check:
    runs-on: self-hosted    
    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: Install WordPress Coding Standards
        run: |
          find . -name composer
          /vendor/composercomposer install
          ./vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.5
          path: tg-instantview/
          standard: WordPress
      