name: WordPress Coding Standards
on: [push]
jobs:
  check:
    runs-on: self-hosted
    container:
      image: composer:2.9.2   
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important!
      - name: Install composer dependencies
        run: |            
            git config --global --add safe.directory /__w/wp-tg-instantview/wp-tg-instantview
            composer install
      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**/*.php"
          phpcs_path: php vendor/bin/phpcs
          standard: WordPress
